### ISSUE TITLE
Can i get raw eye camera data through SDK?

### ISSUE THREAD

**Issue by qwzlh** [FoveHMD/FoveCppSample#2]
Hi, to meet my research need. I need raw eye camera data. Can I get that through SDK APi?

**Comment by sidleal** [comment]
Hi @qwzlh, I'm not sure if it's exactly what you need, but it's possible to capture the eye image bitmaps with the IFVRHeadsetResearch. After trying for a while I finally have a working code. Posted it here:
https://support.getfove.com/hc/en-us/community/posts/360001276093-How-to-use-the-class-IFVRHeadsetResearch?page=1#community_comment_360001906114

**Comment by jbfove** [comment]
After v0.16.0, the API has been updated and the research functionalities, including raw eye camera images, are now part of the SDK and bundled with the SDK and this repo.

The function to get the raw image is Fove::ResearchHeadset::getImage. Make sure to register for the eye image research capability. Also good to keep in mind that the image comes with a standard bitmap header, so make sure to read the header to get the offset to the image data.
